const express = require('express');
const router = express.Router();
var db = require('../config/db');
const uf = require('../functions/analytics');
var acts = express.Router();
acts.get('/allDepts', uf.getAllDept);
acts.get('/allDeptPhase', uf.getAllDeptPhase);
acts.get('/allActHrchy/:id/:deptId', uf.getActivityHchy);
acts.get('/allStatusByRef', uf.getStatusByRef);
acts.get('/allGrByDept/:id/:by', uf.getAllActGroupedByDept);
acts.get('/allGrByCat/:id', uf.getAllActGroupedByCat);
module.exports = acts;